services:
  app:
    command: sh -c "poetry install && poetry run python src/manage.py migrate && poetry run daphne -b 0.0.0.0 -p 8000 docsy.asgi:application"
    build:
        context: backend
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/src/data:/app/src/data
