services:
  app:
    command: sh -c "poetry install && poetry run python src/manage.py migrate && poetry run python src/manage.py runserver 0.0.0.0:8000"
    build:
        context: backend
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/src/db.sqlite3:/app/src/db.sqlite3
