services:
  app:
    command: sh -c "uv sync --frozen && uv run python src/manage.py migrate && uv run daphne -b 0.0.0.0 -p 8000 docsy.asgi:application"
    build:
      context: backend
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src/data:/app/src/data
