# Generated by Django 5.1.3 on 2024-11-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_analysis_analysis_result_analysis_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='status',
        ),
    ]
