# Generated by Django 5.1.3 on 2024-12-01 17:08

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_repomap'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='app_installation_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='enable_pull_request_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='result',
            field=models.JSONField(default=dict, encoder=app.models.PrettyJSONEncoder),
        ),
        migrations.AlterField(
            model_name='repomap',
            name='result',
            field=models.JSONField(default=dict, encoder=app.models.PrettyJSONEncoder),
        ),
    ]
