# Generated by Django 5.1.3 on 2024-12-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_repo_app_installation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='app_installation_id',
        ),
    ]
