# Generated by Django 5.1.3 on 2024-12-10 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='name',
        ),
        migrations.RemoveField(
            model_name='target',
            name='sections',
        ),
        migrations.AddField(
            model_name='target',
            name='repo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.repo'),
            preserve_default=False,
        ),
    ]
