# Generated by Django 5.1.3 on 2024-12-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_target_name_remove_target_sections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='repo',
        ),
        migrations.RemoveField(
            model_name='target',
            name='user',
        ),
    ]
