# Generated by Django 5.1.3 on 2024-12-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='structure',
            field=models.TextField(),
        ),
    ]
