# Generated by Django 5.1.3 on 2024-11-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_github_full_name_repo_nfkc_clone_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
