name: Test backend

on:
  push:
    branches:
      - '**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: getdocsy/docsy

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Also hardcoded in Dockerfile
      - uses: sigoden/install-binary@v1
        with:
          repo: errata-ai/vale
          version: v3.9.1
          platform: linux
          architecture: x86_64

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        working-directory: backend
        run: uv python install
        
      - name: Install dependencies
        working-directory: backend
        run: |
          uv sync --frozen
          
      - name: Run tests
        working-directory: backend
        run: |
          uv run python src/manage.py test