name: Test backend

on:
  push:
    branches:
      - '**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: getdocsy/docsy

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Doesn't allow to only install Vale
      # - uses: errata-ai/vale-action@v2.1.1

      # Also hardcoded in Dockerfile
      - name: Install Vale
        run: |
          wget -q https://github.com/errata-ai/vale/releases/download/v3.9.1/vale_3.9.1_Linux_x86_64.tar.gz && \
          tar -xzf vale_3.9.1_Linux_x86_64.tar.gz && \
          mv vale /usr/local/bin && \
          rm vale_3.9.1_Linux_x86_64.tar.gz

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        working-directory: backend
        run: uv python install
        
      - name: Install dependencies
        working-directory: backend
        run: |
          uv sync --frozen
          
      - name: Run tests
        working-directory: backend
        run: |
          uv run python src/manage.py test